### ISSUE TITLE
Roadmap: Version 3

### ISSUE THREAD

**Issue by MaxMelcher** [MaxMelcher/AzureDevOps.WikiPDFExport#59]
- [x] .NET Framework 5 #43 
- [x]  Include / Exclude capabilities and multi output #39 
- [x]  Rework Logging #58
- [x] Remove [[_TOC_]] from pdf #53 
- [x] Adding frontmatter yaml tags #60 
- [x] Defaulting to [devopswikistyle.css](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/blob/main/AzureDevOps.WikiPDFExport/devopswikistyle.css) #63  

Strech goal
- [ ] Build for Linux #55 
- [ ] Build & Release with GitHub Actions #57

**Comment by MaxMelcher** [comment]
close
