### ISSUE TITLE
Migrate to Puppeteer PDF 

### ISSUE THREAD

**Issue by MaxMelcher** [MaxMelcher/AzureDevOps.WikiPDFExport#77]
Migrating to puppeteer pdf instead of wkhtml. This will potentially allow cross-platform conversion, too.

- [x] styling similar to previous output
- [x] add header and footer options
- [x] including other javascript renderings in one go (mermaid, latex, code highlighting) 
- [x] cross-platform test

**Comment by MaxMelcher** [comment]
Did a quick test - needs styling but should work! 
@AltarBeastiful  

![image](https://user-images.githubusercontent.com/1029559/126779309-7182a939-d215-4c22-bd44-db574f19981b.png)

**Comment by MaxMelcher** [comment]
Puppeteer wont have PDF bookmarks...

**Comment by AltarBeastiful** [comment]
The relevant chromium bug, it could get worked on in the future : 
https://bugs.chromium.org/p/chromium/issues/detail?id=781797

**Comment by MaxMelcher** [comment]
it works pretty well after I figured out how to include images and format the output - but its easier to maintain and style than the wkhtmltopdf stuff...

**Comment by MaxMelcher** [comment]
... latest version also runs on Linux.
